on:
  schedule:
    - cron: '00 12 * * 0-6'
  
  

jobs:
  health_check_schedule:
    runs-on: ubuntu-20.04
    steps:
      - name: Check deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://irene-miao.github.io/child-blog/
          max-attempts: 3
          retry-delay: 5s
      